### ISSUE TITLE
this mod just doen't work and makes pipeworksmapimporter not work anymore

### ISSUE THREAD

**Issue by TheRealGeDev** [herve3527/PatchaMapImporter#1]
it worked a few months ago. I just reinstalled the game and now the game sometimes crashes when loading the community center, looks like that https://cdn.discordapp.com/attachments/691274921518825482/739617012908556418/Capture_decran_60.png, and makes pmi not work anymore

**Comment by herve3527** [comment]
Not reproduced. Patcha map importer is shipped with Frosty'P multiplayer mod since 07/04/2021.
